### ISSUE TITLE
Swift 3/iOS 10 support

### ISSUE THREAD

**Issue by kevinwo** [mathiasnagler/SwiftyAcknowledgements#1]
I'm opening a pull request that offers preliminary support for Swift 3 and iOS 10.

**Comment by falcon03** [comment]
What's the roadmap to a stable releasei ncluding the changes to make this library work with IOS 10/Swift 3?

**Comment by kevinwo** [comment]
Just submitted another pull request for Swift 3 support with the Xcode 8 production release.

https://github.com/mathiasnagler/SwiftyAcknowledgements/pull/6

**Comment by mathiasnagler** [comment]
Swift 3 is now supported.
